picachubaedal/src/main/java/com/kh/picachubaedal/mapper/MemberMapper.java

memberMapper 생성

---

picachubaedal/src/main/java/com/kh/picachubaedal/dao/MemberDao.java

MemberDao 생성

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/FileDownloadController.java
picachubaedal/src/main/java/com/kh/picachubaedal/controller/MemberController.java
picachubaedal/src/main/java/com/kh/picachubaedal/dao/AttachDao.java
picachubaedal/src/main/java/com/kh/picachubaedal/dao/MemberDao.java
picachubaedal/src/main/java/com/kh/picachubaedal/dto/AttachDto.java
picachubaedal/src/main/java/com/kh/picachubaedal/mapper/AttachMapper.java
picachubaedal/src/main/java/com/kh/picachubaedal/service/AttachService.java
picachubaedal/src/main/webapp/WEB-INF/views/member/signup.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/signupFinish.jsp

파일업로드,파일다운로드,마이페이지프사 구현

---

picachubaedal/src/main/java/com/kh/picachubaedal/dto/BasketDto.java
picachubaedal/src/main/java/com/kh/picachubaedal/dto/OrderListDto.java
picachubaedal/src/main/java/com/kh/picachubaedal/dto/PointDto.java
picachubaedal/src/main/java/com/kh/picachubaedal/mapper/BasketMapper.java
picachubaedal/src/main/java/com/kh/picachubaedal/mapper/OrderListMapper.java
picachubaedal/src/main/java/com/kh/picachubaedal/mapper/PointMapper.java

orderList, point, basket DTO,Mapper 생성

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/MemberController.java
picachubaedal/src/main/resources/application.properties
picachubaedal/src/main/webapp/WEB-INF/views/home.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/mypage.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/signin.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/signup.jsp
picachubaedal/src/main/webapp/WEB-INF/views/template/header.jsp

로그인 회원가입페이지 !!!!!

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/FileDownloadController.java
picachubaedal/src/main/java/com/kh/picachubaedal/dao/MemberDao.java
picachubaedal/src/main/webapp/WEB-INF/views/member/mypage.jsp

파일다운로드 및 프로필사진구현

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/PointController.java
picachubaedal/src/main/java/com/kh/picachubaedal/dao/PointDao.java
picachubaedal/src/main/webapp/WEB-INF/views/point/charge.jsp
picachubaedal/src/main/webapp/WEB-INF/views/point/chargeComplete.jsp
picachubaedal/src/main/webapp/WEB-INF/views/point/edit.jsp
picachubaedal/src/main/webapp/WEB-INF/views/point/list.jsp
picachubaedal/src/main/webapp/WEB-INF/views/point/regist.jsp
picachubaedal/src/main/webapp/WEB-INF/views/point/registComplete.jsp

point charge, regist 구현중

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/MemberController.java

회원가입 코드 수정 !!!!!!!!ㅁㄴㅇㄻㄴㅇ

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/StoreController.java
picachubaedal/src/main/java/com/kh/picachubaedal/dao/StoreDao.java
picachubaedal/src/main/java/com/kh/picachubaedal/mapper/StoreMapper.java
picachubaedal/src/main/java/com/kh/picachubaedal/vo/PageVO.java
picachubaedal/src/main/java/com/kh/picachubaedal/vo/StoreVO.java
picachubaedal/src/main/webapp/WEB-INF/views/store/list.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/list2.jsp

삭제된 클래스 복구

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/StoreController.java
picachubaedal/src/main/webapp/WEB-INF/views/store/insert1.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/list2.jsp

가게 등록화면 수정중(기능추가)

---

picachubaedal/src/main/webapp/WEB-INF/views/point/charge.jsp
picachubaedal/src/main/webapp/WEB-INF/views/point/chargeComplete.jsp
picachubaedal/src/main/webapp/WEB-INF/views/point/edit.jsp
picachubaedal/src/main/webapp/WEB-INF/views/point/list.jsp
picachubaedal/src/main/webapp/WEB-INF/views/point/regist.jsp
picachubaedal/src/main/webapp/WEB-INF/views/point/registComplete.jsp

point CRUD 구현과 디자인 완료

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/MemberController.java

MemberController 충돌 문제 해결

---

picachubaedal/src/main/webapp/WEB-INF/views/point/charge.jsp

charge 페이지 디자인 수정

---

picachubaedal/src/main/java/com/kh/picachubaedal/dao/StoreDao.java
picachubaedal/src/main/java/com/kh/picachubaedal/dto/StoreDto.java
picachubaedal/src/main/java/com/kh/picachubaedal/mapper/StoreMapper.java
picachubaedal/src/main/webapp/WEB-INF/views/store/insert1.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/insert2.jsp

03.14 등록페이지 구현중ㅜㅜㅜㅜ

---

picachubaedal/src/main/java/com/kh/picachubaedal/dao/StoreDao.java
picachubaedal/src/main/java/com/kh/picachubaedal/dto/StoreDto.java
picachubaedal/src/main/java/com/kh/picachubaedal/mapper/StoreMapper.java
picachubaedal/src/main/webapp/WEB-INF/views/store/insert1.jsp

03.15 가게등록관련

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/StoreController.java
picachubaedal/src/main/java/com/kh/picachubaedal/dao/StoreDao.java

controller, dao insert 부분 변경

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/MemberController.java
picachubaedal/src/main/webapp/WEB-INF/views/home.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/signin.jsp

컨트롤러 memberno 세션 값 삭제 추가

---

picachubaedal/src/main/java/com/kh/picachubaedal/vo/PageVO.java
picachubaedal/src/main/webapp/WEB-INF/views/menu/ceoMenuList.jsp
picachubaedal/src/main/webapp/WEB-INF/views/menu/customerMenuList.jsp

메뉴 리스트 메뉴담기 제외 구현

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/StoreController.java
picachubaedal/src/main/java/com/kh/picachubaedal/dao/StoreDao.java
picachubaedal/src/main/java/com/kh/picachubaedal/dto/StoreDto.java
picachubaedal/src/main/java/com/kh/picachubaedal/mapper/StoreMapper.java
picachubaedal/src/main/webapp/WEB-INF/views/member/signin.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/change.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/detail.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/insert1.jsp
picachubaedal/src/main/webapp/WEB-INF/views/template/header.jsp

가게정보수정 완료(이미지 수정 보완예정)

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/CartController.java
picachubaedal/src/main/java/com/kh/picachubaedal/dao/CartDao.java
picachubaedal/src/main/java/com/kh/picachubaedal/dto/CartDto.java
picachubaedal/src/main/java/com/kh/picachubaedal/mapper/CartMapper.java
picachubaedal/src/main/webapp/WEB-INF/views/cart/insert.jsp
picachubaedal/src/main/webapp/WEB-INF/views/cart/insertComplete.jsp

장바구니등록 1차 구현 DB저장

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/MenuController.java

fix: 메뉴 컨트롤러 코드 수정

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/CartController.java
picachubaedal/src/main/java/com/kh/picachubaedal/dao/CartDao.java

장바구니 리스트 수정

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/StoreController.java
picachubaedal/src/main/java/com/kh/picachubaedal/service/ImageService.java
picachubaedal/src/main/webapp/WEB-INF/views/store/categoryList.jsp

카테고리가게리스트에 사진주소추가

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/MemberController.java
picachubaedal/src/main/java/com/kh/picachubaedal/controller/OrdersController.java
picachubaedal/src/main/java/com/kh/picachubaedal/controller/StoreController.java
picachubaedal/src/main/java/com/kh/picachubaedal/dto/OrdersDto.java
picachubaedal/src/main/java/com/kh/picachubaedal/dto/StoreDto.java
picachubaedal/src/main/java/com/kh/picachubaedal/logic/DistanceCalculator.java
picachubaedal/src/main/java/com/kh/picachubaedal/logic/KakaoGeoResponse.java
picachubaedal/src/main/java/com/kh/picachubaedal/logic/Location.java
picachubaedal/src/main/java/com/kh/picachubaedal/logic/MapService.java
picachubaedal/src/main/java/com/kh/picachubaedal/mapper/OrdersMapper.java
picachubaedal/src/main/webapp/WEB-INF/views/orders/buy.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/categoryList.jsp

거리계산기능 구현 및 관련코드 전부

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/OrdersController.java
picachubaedal/src/main/java/com/kh/picachubaedal/dao/OrdersDao.java
picachubaedal/src/main/webapp/WEB-INF/views/orders/buy.jsp
picachubaedal/src/main/webapp/WEB-INF/views/orders/buyComplete.jsp

구매페이지 구현 중

---

picachubaedal/src/main/java/com/kh/picachubaedal/dao/OrdersDao.java
picachubaedal/src/main/java/com/kh/picachubaedal/service/OrdersService.java
picachubaedal/src/main/webapp/WEB-INF/views/orders/buy.jsp

구매 등록 에러수정

---

picachubaedal/src/main/webapp/WEB-INF/views/menu/customerMenuList.jsp

가게정보 메뉴리스트 디자인제외 기능구현

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/OrdersController.java
picachubaedal/src/main/java/com/kh/picachubaedal/controller/ReviewBoardController.java
picachubaedal/src/main/java/com/kh/picachubaedal/dao/OrdersDao.java
picachubaedal/src/main/java/com/kh/picachubaedal/dto/OrdersDto.java
picachubaedal/src/main/java/com/kh/picachubaedal/service/OrdersService.java
picachubaedal/src/main/webapp/WEB-INF/views/orders/buyList.jsp

주문내역 가게사진 , 가게이름 추가

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/OrdersController.java
picachubaedal/src/main/webapp/WEB-INF/views/member/mypage.jsp
picachubaedal/src/main/webapp/WEB-INF/views/menu/customerMenuList.jsp
picachubaedal/src/main/webapp/WEB-INF/views/orders/buyComplete.jsp

구매하면장바구니 비우기, 품절상품 메뉴담기 불가,마이페이지 디자인 수정,구매완료페이지문구 수정

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/StoreController.java
picachubaedal/src/main/webapp/WEB-INF/views/store/likeList.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/list.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/list2.jsp

내가게 클릭시 주소 수정 내가게 리스트 이미지 클릭시 해당가게 이동

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/CartController.java
picachubaedal/src/main/webapp/WEB-INF/views/menu/customerMenuList.jsp

장바구니 담기(동기)후 가게페이지 유지기능추가

---

picachubaedal/src/main/webapp/WEB-INF/views/member/findIdFail.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/findIdSuccess.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/findPwSuccess.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/profileEdit.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/pwUpdateSuccess.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/signin.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/signup.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/signupFinish.jsp
picachubaedal/src/main/webapp/WEB-INF/views/menu/customerMenuList.jsp

member jsp살짝수정

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/MemberController.java
picachubaedal/src/main/java/com/kh/picachubaedal/service/AttachService.java

마이페이지 이미지변경 수정

---

picachubaedal/src/main/webapp/WEB-INF/views/menu/ceoMenuList.jsp

fix: menuList card 수정

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/StoreController.java

store/list이미지 오류 수정

---

picachubaedal/src/main/webapp/WEB-INF/views/store/change.jsp

가게 정보 수정 가능, 헤더풋터 추가

---

picachubaedal/src/main/java/com/kh/picachubaedal/controller/PointController.java
picachubaedal/src/main/java/com/kh/picachubaedal/controller/StoreController.java
picachubaedal/src/main/java/com/kh/picachubaedal/controller/Test.java
picachubaedal/src/main/java/com/kh/picachubaedal/interceptor/Member2Interceptor.java
picachubaedal/src/main/resources/application.properties
picachubaedal/src/main/webapp/WEB-INF/views/cart/list.jsp
picachubaedal/src/main/webapp/WEB-INF/views/member/signup.jsp
picachubaedal/src/main/webapp/WEB-INF/views/menu/ceoMenuList.jsp
picachubaedal/src/main/webapp/WEB-INF/views/menu/customerMenuList.jsp
picachubaedal/src/main/webapp/WEB-INF/views/menu/edit.jsp
picachubaedal/src/main/webapp/WEB-INF/views/menu/insert.jsp
picachubaedal/src/main/webapp/WEB-INF/views/orders/buyList.jsp
picachubaedal/src/main/webapp/WEB-INF/views/point/regist.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/detail.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/insert1.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/insert2.jsp
picachubaedal/src/main/webapp/WEB-INF/views/store/likeList.jsp

 ajax,구매,카트 주소 수정
